name: deploy nook-frame
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #  your build commands
      # - run: |
      #    ng build --prod
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod' #Optional
          vercel-project-id: prj_umqQVpUYTteW2TVKX16LDKGADA33 #Required 
          vercel-org-id: 0K8HAoJGVWDdqFyynTzuYPN7
          working-directory: ./